server:
  port: 8081
login:
  user:
    username: superadmin
    # 123456
    password: "{bcrypt}$2a$10$0EQexC0XYw58x.ys.Ym8QO3H2Llr0G4wEAFddm8PkOUGy6hQraaui"
    roles:
      - roleName: 超级管理员
        permissionInfos:
          - urlName: 所有权限
            url: /**
spring:
  profiles:
    active: datasource, gateway