spring:
  datasource:
      url: jdbc:mysql://192.168.110.130:3306/security_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root
      # 数据库驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        web-stat-filter:
          enabled: false
        stat-view-servlet:
          enabled: false
        # druid监控拦截
        filters: stat
        # 最大连接数
        max-active: 20
        # 初始化连接数
        initial-size: 1
        # 最大等待响应时间（毫秒）
        max-wait: 60000
        # 最小连接数
        min-idle: 1
        # 配置心跳 检测需要关闭的空闲连接时间（毫秒）
        time-between-eviction-runs-millis: 60000
        # 连接在连接池中最小生存时间（毫秒）
        min-evictable-idle-time-millis: 30000
        # 检测连接是否有效
        validation-query: select 'x'
        # 建议配置为true，不影响性能，并且保证安全性。
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，
        # 执行validationQuery检测连接是否有效。
        test-while-idle: true
        # 申请连接时执行validationQuery检测连接是否有效,设置true会降低性能
        # 这里设置为true防止取到的链接不可用
        test-on-borrow: true
        # 归还连接时执行validationQuery检测连接是否有效,设置true会降低性能
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小  如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。
        pool-prepared-statements: false
        # 使用 sqlite 需要把值设置为小于 0
        max-open-prepared-statements: 20
  data:
    redis:
      host: 192.168.110.130
      port: 6379
      password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml