spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.webRoot}
#允许访问的文件路径
web:
  ## 打包后使用与jar包相对路径即可
  ## 如jar包同级存在web目录： \web
  webRoot: D:\work\workspace\github\spring-cloud-gateway-security\web