spring:
  security:
    antpatterns: "/web/dist/**,/web/websocket.html"
    csrf-enable: false
    source-ip-enable: false
    # IP 白名单认证开关，默认关闭
    ip-whitelist-enable: false
    # MAC 白名单认证开关，默认关闭
    mac-whitelist-enable: false