spring:
  cloud:
    gateway:
      session:
        # 不限制Session过期时间（转发时生效）：-1 单位：分钟
        timeout: 30
        # 不限制登录人数：-1
        maxSessions: 10000
      default-filters:
        - Session
      routes:
        - id: server_route
          # 转发地址
          uri: http://127.0.0.1:8080
          predicates:
            # 拦截请求路径
            - name: Path
              args:
                matcher: /gateway/**
#            - Path=/gateway/**
          filters:
            # 跳过1个前缀
            - name: StripPrefix
              args:
                # 此处 key 必须为 “parts”
                parts: 1
#            - StripPrefix=1
            # token身份认证 JwtCheckGatewayFilterFactory
            - TokenCheck
            # 请求流量限制，默认5MB
            - name: RequestSize
              args:
                maxSize: 5000000
        # sockJS路由需要与websocket路由结合使用
        - id: sockJS_route
          uri: http://10.1.7.81:8081
          predicates:
            - Path=/websocket/**
        - id: websocket_route
          uri: ws://localhost:8081
          predicates:
            - Path=/websocket/**
      # 开启/关闭网关
      enabled: true
      loadbalancer:
        use404: true
  application:
    name: gateway
  static:
    antpatterns: "/dist/**"