spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            ## 负载均衡地址
            providerService:
              - uri: http://1.1.1.1:8080
              - uri: http://1.1.1.2:8080
    loadbalancer:
      healthCheck:
        ## 健康检查地址， 可以采用服务其中一个地址作为健康检查地址
        path:
          providerService: /health/healthCheck
        ## 健康检查初始延迟
        initialDelay: 0
        ## 重新运行健康检查周期间隔
        interval: 5s
      ##
      configurations: health-check